// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcNTwTCceajQWxAPEHMCoBG3xXbJ83InM',
    appId: '1:668160646864:web:1ce2455222f482902508d5',
    messagingSenderId: '668160646864',
    projectId: 'metgun-haber',
    authDomain: 'metgun-haber.firebaseapp.com',
    storageBucket: 'metgun-haber.firebasestorage.app',
    measurementId: 'G-6RHPRX7B5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe4EyHjO3dcL0YOjVOUs8U9Bi_F8ookC4',
    appId: '1:668160646864:android:b26030d0fad078d42508d5',
    messagingSenderId: '668160646864',
    projectId: 'metgun-haber',
    storageBucket: 'metgun-haber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtXcTLm4jh_98o18whEemWsuA5aSwqO7M',
    appId: '1:668160646864:ios:e14cf3147c10e7482508d5',
    messagingSenderId: '668160646864',
    projectId: 'metgun-haber',
    storageBucket: 'metgun-haber.firebasestorage.app',
    androidClientId: '668160646864-mric6r2uth9l1r0u52e17smantsbvkkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtXcTLm4jh_98o18whEemWsuA5aSwqO7M',
    appId: '1:668160646864:ios:e14cf3147c10e7482508d5',
    messagingSenderId: '668160646864',
    projectId: 'metgun-haber',
    storageBucket: 'metgun-haber.firebasestorage.app',
    androidClientId: '668160646864-mric6r2uth9l1r0u52e17smantsbvkkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcNTwTCceajQWxAPEHMCoBG3xXbJ83InM',
    appId: '1:668160646864:web:92ee993f291fc5c12508d5',
    messagingSenderId: '668160646864',
    projectId: 'metgun-haber',
    authDomain: 'metgun-haber.firebaseapp.com',
    storageBucket: 'metgun-haber.firebasestorage.app',
    measurementId: 'G-YT7YV9G172',
  );

}